dist: trusty
language: java
jdk:
- oraclejdk9

before_install:
 - chmod +x gradlew
 
script:
 - ./gradlew clean check test javadoc fatCapsule apiJar

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: "3i/a2FBLGULwCFI0TOU0DcyMpcT8PY4iedHc63uXqxoVaAVIMjQP6mTK0Y4URgGgy2SSu5y3yosfXM4m8iqzdCn1vdkicYhEWuV6qldZrc2kCRoPLAKRJ63Rnwjsf14aTJHT2BYVSIGPZ/UcSNqSc/rOyjYktfM7BSYOWb4rVJLWLgCEPV9MYkYJC3fWQjKSUK4lW148OCm2XvVINrOBgzwRlOHFfZ0YdUzk9sMUHCi3IQ5n/wTT/CI84IoahLMLbqm9y4LFWSjM7GDuHEDcDiQ/oBqzstGR0SOZWocWg9chsY+YJacSlfwG47NZRgq+74e+erHICmS6vmReb54HZTmmQ27QbWLZ1J/gHq2At4IHKYbuQZmgXFFoYcl0OlFCS9E1uNcMTCCc2KjYYyNDK52nEQBbqfm0fcIr7aptkM/qyoU/6pM+tHID2iOeb6Hl6fksPXbEcQ82PNM2aSDzWiG15Rml14as95qdTS8UampFCvyIDEpoxBp4XOvrTPsvyP3z+kiafUUbilMUf5NWpdYQSz2XNTACjfq19c15iczRnTZFOtx/ApWIqJLXzPuAFF1RcA0OxEbVpY/II2GiBWCQQQHe76TzhRn2ZID1Ozg421S5+/oWO8yIO8GGRjCaUBxTAmw3W8Lq+eVWekeEVDeNmeXaZtVfiDktTlP30c4="
  file:
    - "build/libs/Wingman.jar"
    - "build/libs/Wingman-api.jar"
    - "build/libs/Wingman-core.jar"
  on:
    tags: true

after_deploy:
 - git config --global user.name "WingmanUpdater"
 - git config --global user.email "wingmanosrs@gmail.com"
 - git clone https://github.com/Wingman/wingman.github.io.git
 - cd wingman.github.io
 - git remote rm origin
 - git remote add origin https://wingmanupdater:$GH_TOKEN@github.com/Wingman/wingman.github.io.git
 - mkdir docs
 - git rm docs/*
 - cp -R ../build/docs/javadoc/* docs
 - git add docs/*
 - git commit -m "Update Javadocs"
 - git push -fq origin master
 
env:
  global:
    secure: "qLFGip3S8XyYQjfr0wrhHOestTFiVfFuS5MUomz97tXra/aFsHcBQU1V15uDb8/3q86h9xuNel1aA2gBZILN3qa3x0oHSuNm0x27CC1MaMwEH8EqK+klGFga9d9GtWn/HhS77x1wA7eR4eBb9vxSgRglqt5Se5ovu8faOvF6IAb1l02Pxihad/62F78Z4804sVInxjBBNI/mApK0fgQfYJmI7z8DtKS98NhqSJTkd7m14709ELrvgKFoOlWVGqKZmgPH9sdOMwOv3yGk5DjWca8+Q9j/2ILxfIHTdjgrDIx4Xvey5f1uaq9JDTOvAZaYCxd3gsh5GrFjAF5cF/6gFISFlRWL3LoiA1PGWe50XmCzLiNpPxoJr0P1dD1h6e5SHcxLFI4SPj4s6Ba4ofo8EECsAYIWB4A9hCaCyiG9xOgNMN2ICj8by2fFEWyrqwSw63uubrbc25kqnMPywa25QNwlB7voprcxJfYfxHuM1wh4VNHbp1IYBDKwfuZmIrTI5BOuoEjzrgz2rPmGFdqYQz93YdFn8tQ43u8QJ58wrHxLNXjfZyTkarS11e5ct8plog/vKnz3w+A4hT/sO5gMsLhn4ai9GxOkefJ+vV3xWh4ukurQmvNkOzK02kM6ze0x+pyhkUzVW0L6IZUXxsuEP2FlY2q2C9/gSPrjNOUWHZM="

notifications:
  slack:
    secure: "ZoDPu3EExfbtptp02jqpWb6X3kuEHnG8mcB0fLsS/sL2gu5Xp3mU5sJL6DCaFlgToOXIu07JpKrMYRF0rJLq0wutd/ysp3NRO3Gj8ZdhnwvhvSpSVEvr4aeys2DKGTX1x6WCTrank1bTmG7fjP9Uh5nf1PQSPYR83Ry997fu1ybsruxx4PZqo/vQEAiMQM/G9tsbfrt6mEMz24twyla3MXY2uKP9xP9Xvf++hg/ZFkhiQXn/G7ko6PegS+YE6VsR+dGKgh9k3YGhWsDquvz8PQQQmF1i35w3AwATSsYQyvaucUZgRHGY+xC6NswvN0zkHyLQbTVySh5c4N8JM0i7Eb0Mvls62Fmb5DQePuPYfzazlyfnPd8xj2gTkkxhviaI+WRsjMbbNd0d0aQOfo6NM78mAiVSFIVQUuILIY36TJ5PzlMTSqaKDDZIM7OGh23Z1+5NCH1pbVbL4+UVmcevzt3k4cJgNi8V+keODgCS+UOmFCUvlyggkRKwxZXlWtxJvayX4p/m02YIeo5AdHQe5sAaGJBlhlh44Pt7AiRUtjAICAYFlWEbvrPHVZXC9WL3z3lWaBaAzrmwRygofUKMrQjchK07ukk6D5ncZVC9s0N/wRlXtqmW/trECaveIUqZHSOde6t2liO737CDuKcpUEUhNqcKbmVzVjPOZ+RByiQ="
