language: java

before_install:
 - chmod +x gradlew
 
script:
 - ./gradlew clean check test javadoc fatCapsule

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: "PLmAomRzcW3qT6hl+cFZT5rGyxmpMVqnK05gb32/uTeI3Z7hWHkfgZeuSLhEb69/G22QBP4gedDjXdjuxXxpXosguHczZh7dsOlb80R94YJf4zPMoI5fydBZOesqY5/wl3NYHjJqbptk4z4mog2R7eSvdHy1f5KmD0YrWfsI+D8qqc5QQH7hHC1npw1ST3uL1LXMHU6tD+x+1ST2WmTXJh9jbDBdp9HZxvVMNchgadAwJcb6Gxk2qVF1fJPdcG78nqndOC5wfzIgUwixd+VWyRNX/0o8oUC4MISHbVR7a/MdBoA3bNOxUELEUEwOFCJoAV5U8FhmlVMn5VEbdh5hIXNLf73DvcOrJtuTCjgniD/n0ZKGMXFIbxlVZUIhWUcW/LFjMLq1Ugb/M/MuoYDnKRQTKdzve71RbFhF26DXBTqJIXPfoUfvpaad2JVgB5Tg1gfHE0515P8mYDiOYQw1oJFlSTrAkwzVh8Z8ma7+NtzKHu8KLpSafcvHWMKGRQiy9sbV49eXtgMjiitfcuIbQ+EtmRYrRXWVkYSr+S4OKVjuPdFCEDJn7339NO7nuP5u5FPyrmF5dEwyv7hEhfrFJJkOTyChNr8AA9qG13K6/Pl2G/0XffompEOK6PA+JpywTv/PQ6xny9+/i1KzQIH+ugaM+qzHyGgxaIaFkqevz38="
  file:
    - "build/libs/Wingman.jar"
    - "build/libs/Wingman-api.jar"
    - "build/libs/Wingman-core.jar"
  on:
    tags: true

after_deploy:
 - git config --global user.name "WingmanUpdater"
 - git config --global user.email "wingmanosrs@gmail.com"
 - git clone https://github.com/Wingman/wingman.github.io.git
 - cd wingman.github.io
 - git remote rm origin
 - git remote add origin https://wingmanupdater:$GH_TOKEN@github.com/Wingman/wingman.github.io.git
 - mkdir javadoc
 - git rm javadoc/*
 - cp -R ../build/docs/javadoc/* javadoc
 - git add javadoc/*
 - git commit -m "Update Javadoc"
 - git push -fq origin master
 
env:
  global:
    secure: O9wqaX3BD+8sOVXKgtCGo4+Sr6Rl6DFQv/fh9T3pqW9JQOmpOCrhNCe/IkV3fftd1zMPV2wxXJiPgfwP9Nl49l3tCxtRciJ+wHGQvivfyoOEiHRBcueTfQgLcuFwaP72IFOgMuGt2rdOWaiFs+1KytJpWGp6RrZh7plrp7Z/YLDvqqjH98AUGNfIIg4iV7qDd0hza/4J5fyl/GHErIGmfgjrbNSRB8Q9Ey99g++4wVK+4KBCt6CJFLtuf3FWqJ3GFa20d8YDNlvFCbJ6o9/xoihD2UNm86juxu7YlszQC6sUSZ8K53d1RZLXgOM+qAlGCOSR9wwic7sS51UdGg6E4W9B38Rv5YfEPkorAJHVU3fVp8cKH11J6neVj2Pb0JvL2eK8sfVqGnvEw5lYCvj0sb1GFj7sWqZVhSg0s7L2x9HenEiuqOLLDkcAYaBhPmw8mrtLbJ8ioRgs0aB8Dznia4Hi1pNNwFMtTye3YlAdlsWZZAD7IUOUXQl6SZT8+E3zgpKDbOMeauHU4g186fKcOxo8ivGCZDTw81R5FkCHnJWzofRWMNJhZR9OoEDb/gMZzEfUHRYV7RNDAbvhyrUHsQf+m7XKzKpPogTPQB5MWiBhKiGhQJUHilZTl2tz3lxOL/N28fqmswh5Hw3fafXyjzxzun6fXDVNUPJsrvMkiS0=

notifications:
  slack:
    secure: ZoDPu3EExfbtptp02jqpWb6X3kuEHnG8mcB0fLsS/sL2gu5Xp3mU5sJL6DCaFlgToOXIu07JpKrMYRF0rJLq0wutd/ysp3NRO3Gj8ZdhnwvhvSpSVEvr4aeys2DKGTX1x6WCTrank1bTmG7fjP9Uh5nf1PQSPYR83Ry997fu1ybsruxx4PZqo/vQEAiMQM/G9tsbfrt6mEMz24twyla3MXY2uKP9xP9Xvf++hg/ZFkhiQXn/G7ko6PegS+YE6VsR+dGKgh9k3YGhWsDquvz8PQQQmF1i35w3AwATSsYQyvaucUZgRHGY+xC6NswvN0zkHyLQbTVySh5c4N8JM0i7Eb0Mvls62Fmb5DQePuPYfzazlyfnPd8xj2gTkkxhviaI+WRsjMbbNd0d0aQOfo6NM78mAiVSFIVQUuILIY36TJ5PzlMTSqaKDDZIM7OGh23Z1+5NCH1pbVbL4+UVmcevzt3k4cJgNi8V+keODgCS+UOmFCUvlyggkRKwxZXlWtxJvayX4p/m02YIeo5AdHQe5sAaGJBlhlh44Pt7AiRUtjAICAYFlWEbvrPHVZXC9WL3z3lWaBaAzrmwRygofUKMrQjchK07ukk6D5ncZVC9s0N/wRlXtqmW/trECaveIUqZHSOde6t2liO737CDuKcpUEUhNqcKbmVzVjPOZ+RByiQ=
